- README.md
Proposal file updated based on https://github.com/smartdevicelink/sdl_evolution/pull/760.  README updated to reflect new proposal file.
> update README to reflect accepted revisions to proposal

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Adds the template files for Github so that we don't get PRs like this.
> Add github template files

- lib/js/protocol/SdlProtocolBase.js
- lib/js/transport/SdlPsm.js
- lib/js/transport/TransportBase.js
- lib/js/transport/TransportListener.js
- lib/node/transport/WebsocketServer.js
- lib/node/transport/WebsocketServerConfig.js
- Finished the `SdlPsm` class
- Started to integrate `SdlPsm` into other classes
- Some work needs to be looked over before merging to mainline, but this PR only merges to feature branch
> Finish SdlPsm

- lib/js/protocol/MessageFrameAssembler.js
- lib/js/protocol/SdlPacket.js
- lib/js/protocol/SdlProtocolBase.js
- lib/js/protocol/SdlProtocolListener.js
- lib/js/protocol/enums/ServiceType.js
- lib/js/rpc/RpcMessage.js
- lib/js/session/SdlSession.js
- lib/js/session/SdlSessionListener.js
- lib/js/transport/TransportConfigBase.js
- lib/js/transport/TransportListener.js
- lib/js/util/JsonRpcMarshaller.js
Fixes #[issue number]
This PR is **not ready** for review.
- This PR will contain changes to create the protocol layer and any support for that layer
> SdlProtocol Base

- .eslintignore
- .eslintrc.json
- lib/node/package.json
- package-lock.json
- package.json
Fixes #21 
* Verify ESLint performs automatic checks in a small sample of IDEs (such as Atom IDE or Visual Studio Code), using the ESLint configuration.
* Manually execute ESLint using the new NPM scripts in `./package.json`.
Adds ESLint dependencies, ESLint configuration, ESLint ignore list, and ESLint manual NPM scripts.
* None
* Adds support for ESLint
* None
* None
> Add eslint configuration

- lib/js/src/protocol/BinaryFrameHeader.js
Fixes #25 
This PR makes **major** API changes.
This should be tested with and without bulk data set. PutFile and GetFile are good to use for bulk data. ShowMessage is a simple RPC without bulk data.
Implements the binary frame header assembler/parser.
> BinaryFrameHeader implementation.

- lib/js/src/rpc/enums/FunctionID.js
Fills in missing FunctionID.js enums
> Fill out function id enums

- lib/js/src/rpc/structs/ButtonCapabilities.js
- lib/js/src/rpc/structs/DisplayCapabilities.js
- lib/js/src/rpc/structs/Grid.js
- lib/js/src/rpc/structs/Image.js
- lib/js/src/rpc/structs/ModuleInfo.js
- lib/js/src/rpc/structs/PresetBankCapabilities.js
- lib/js/src/rpc/structs/SoftButtonCapabilities.js
Removed references to non existent setValue method
> Remove setValue

- GUIDELINES.md
Fixes #15 
Not applicable.
Updates and additions to the contribution guidelines, mostly for automated RPC class generation.
> Contribution Guideline Updates

- lib/node/src/transport/TransportManager.js
- lib/node/src/transport/WebSocketServer.js
- lib/node/src/transport/WebSocketServerConfig.js
> Linter fix

- generator/mapping.json
- generator/templates/scripts/GetVehicleDataRequest.js
- generator/templates/scripts/GetVehicleDataResponse.js
- generator/templates/scripts/SubscribeVehicleDataRequest.js
- generator/templates/scripts/SubscribeVehicleDataResponse.js
- generator/templates/scripts/UnsubscribeVehicleDataRequest.js
- generator/templates/scripts/UnsubscribeVehicleDataResponse.js
- lib/js/src/rpc/messages/GetVehicleData.js
- lib/js/src/rpc/messages/GetVehicleDataResponse.js
- lib/js/src/rpc/messages/SubscribeVehicleData.js
- lib/js/src/rpc/messages/SubscribeVehicleDataResponse.js
- lib/js/src/rpc/messages/UnsubscribeVehicleData.js
- lib/js/src/rpc/messages/UnsubscribeVehicleDataResponse.js
Fixes #135 
Testing instructions at https://bitbucket.org/livio/sdl-test-suite-android/src/a63e1eaac56ba0d97d7981551ca7f62399d5f4a1/sdl_test_suite/baseTests/src/main/java/baseTests/BaseTestRunner.java?detectloginloop#lines-814
Added custom scripts to include OEM Custom Vehicle Data methods upon generation.
> Add OEM Custom Vehicle Data methods to RPC Generator

- examples/node/hello-sdl/AppClient.js
Fixes #156  
Changes the logic around so that the managers are in a ready state by the time the main app runs
> Reorder node cloud app logic so that managers are ready before executing

- examples/webengine/hello-sdl/readme.md
- lib/js/src/protocol/MessageFrameDisassembler.js
- lib/js/src/protocol/SdlProtocolBase.js
- lib/js/src/rpc/RpcMessage.js
- lib/js/src/rpc/RpcResponse.js
- lib/js/src/transport/WebSocketClientConfig.js
Fixes documentation in several files, and includes additional information in the webengine app readme for the case where core doesn't support the websocket server yet
> Documentation updates

- lib/js/app.js
- package-lock.json
- package.json
Updates the build files and the package.json version from 0.2.0 to 1.0.0
> Update build files and package version

- lib/js/app.js
- lib/js/src/manager/lifecycle/LifecycleManager.js
- lib/js/src/session/_SdlServiceListener.js
- lib/js/src/session/_SdlSession.js
- lib/js/src/session/_SdlSessionListener.js
- lib/js/src/session/_ServiceListenerMap.js
Ensure unit tests pass and example apps run successfully.
Privatizes session layer components.
> Privatize Session Layer

- lib/js/src/manager/screen/VoiceCommandManagerBase.js
- lib/js/src/manager/screen/utils/VoiceCommand.js
setCommandId and getCommandId of VoiceCommand are now private
> Privatize methods

- lib/js/src/protocol/SdlProtocolBase.js
- lib/js/src/rpc/RpcMessage.js
Changes RpcMessage's method names to setPayloadProtected and isPayloadProtected
> Change encryption method names

- lib/js/src/manager/_SubManagerBase.js
- lib/js/src/protocol/SdlProtocol.js
- lib/js/src/protocol/_SdlProtocolBase.js
- lib/js/src/transport/CustomTransport.js
- lib/js/src/transport/_SdlPsm.js
- lib/js/src/transport/_SslConfig.js
- lib/js/src/transport/_TransportBase.js
- lib/js/src/transport/_TransportCallback.js
- lib/js/src/transport/_TransportConfigBase.js
- lib/js/src/transport/_TransportListener.js
- lib/js/src/transport/_TransportManager.js
- lib/js/src/transport/_TransportManagerBase.js
- lib/js/src/transport/_WebSocketClient.js
- lib/js/src/transport/util/_TransportRecord.js
- lib/node/src/transport/_TcpClient.js
- lib/node/src/transport/_TransportManager.js
- lib/node/src/transport/_WebSocketServer.js
Any class in the transport layer that can't be directly used by the developer is now private
> Privatize transport layer

- lib/js/src/manager/SdlManager.js
SdlManager's initialize method is now private
> SdlManager initialize private

- lib/js/src/manager/SdlManager.js
- lib/js/src/manager/_SdlManagerBase.js
initNotificationQueue method is now removed.
> Remove unused method

- generator/templates/function_template.js
- lib/js/src/manager/SystemCapabilityManager.js
- lib/js/src/manager/lifecycle/_LifecycleManager.js
- lib/js/src/protocol/_MessageFrameDisassembler.js
- lib/js/src/rpc/RpcMessage.js
Change getFunctionName and setFunctionName to getFunctionId and setFunctionId
> Change method name in rpcmessage

- generator/templates/RpcCreator_template.js
- lib/js/src/manager/file/FileManager.js
- lib/js/src/manager/lifecycle/_LifecycleManager.js
- lib/js/src/manager/permission/_PermissionFilter.js
- lib/js/src/protocol/_MessageFrameDisassembler.js
- lib/js/src/protocol/_SdlPacket.js
- lib/js/src/protocol/_SdlPacketFactory.js
- lib/js/src/protocol/_SdlProtocolBase.js
- lib/js/src/protocol/_SdlProtocolListener.js
- lib/js/src/rpc/RpcCreator.js
- lib/js/src/session/_SdlSession.js
- lib/js/src/streaming/video/_VideoStreamingParameters.js
- lib/js/src/transport/CustomTransport.js
- lib/js/src/transport/TransportCallback.js
- lib/js/src/transport/_TransportBase.js
- lib/js/src/transport/_TransportManagerBase.js
- lib/js/src/transport/_WebSocketClient.js
- lib/js/src/util/_ArrayTools.js
- lib/js/src/util/_BitConverter.js
- lib/js/src/util/_Bson.js
- lib/js/src/util/_FileUtils.js
- lib/js/src/util/_JsonRpcMarshaller.js
- lib/js/src/util/_TextEncoder.js
- lib/js/src/util/_uuid.js
- lib/node/src/transport/_TcpClient.js
- lib/node/src/transport/_WebSocketServer.js
- lib/node/src/util/_FileUtils.js
Finishes modifying the scope of classes not to be used by the developer to be private. Also converts TransportCallback to public, as it is used in a public method in the CustomTransport class.
> Modify class scopes

- lib/js/src/manager/SystemCapabilityManager.js
- lib/js/src/manager/_SdlManagerBase.js
- lib/js/src/manager/lifecycle/_LifecycleManager.js
Removed some TODOs that were either unnecessary or unhelpful.
> Remove unnecessary todos

- examples/node/hello-sdl-tcp/index.js
- examples/node/hello-sdl/AppClient.js
- lib/js/app.js
Updates the build files and fixes the build references in the node example apps
> Update builds and build references in example apps

- lib/js/src/manager/permission/_PermissionFilter.js
- lib/js/src/util/_uuid.js
With the uuid library only being used for one basic case, this PR changes the uuid generator to something easy and custom to avoid licensing issues.
> Change implementation of uuid library with own code

- lib/js/src/manager/screen/_ScreenManagerBase.js
- lib/js/src/manager/screen/_SoftButtonManager.js
- lib/js/src/manager/screen/_TextAndGraphicManager.js
- lib/js/src/manager/screen/_TextAndGraphicManagerBase.js
- lib/js/src/manager/screen/_VoiceCommandManager.js
- lib/js/src/manager/screen/utils/SoftButtonObject.js
Make the soft button, voice, and text and graphic internal managers private
> Make the internal managers private

- tests/managers/AppClient.js
- tests/managers/index.js
- tests/managers/lifecycle/LifecycleManagerTests.js
- tests/managers/screen/ScreenManagerTests.js
- tests/managers/screen/SoftButtonManagerTests.js
- tests/node/streaming/video/VideoStreamingParametersTest.js
- tests/node/util/BitConverterTest.js
- tests/node/util/BsonTest.js
Update the unit tests based on all the changes to making classes private in the library. Note that a small refactor of the manager tests was also made so that the tests pass there, but a more substantial change will be necessary post-release.
> Update unit and manager tests

- lib/js/src/manager/lifecycle/_LifecycleManager.js
Fixes #230 
Sets the tts names and vr synonyms to the RAIR from the lifecycle config object.
> Pass in tts names and vr synonyms from config

- .github/PULL_REQUEST_TEMPLATE.md
This PR is **[ready]** for review.
This PR makes **[no]** API changes.
Updated PR review request from nickschwab to crokita.
> update PR review request info

- lib/js/src/manager/SystemCapabilityManager.js
Fixes #224 
Adds get methods to access certain SCM capabilities. Get methods for Button and SoftButton were excluded as they already exist in the default main window capability
> Make some of the SCM capabilities public

- lib/js/app.js
- lib/js/src/manager/SystemCapabilityManager.js
- lib/js/src/manager/_ManagerUtility.js
- lib/js/src/manager/screen/_TextAndGraphicManagerBase.js
Fixes #178 and #270
This PR addresses the change needed for moving capability checks to the SCM, as well as better aligning the JS Suite's TextAndGraphicManager with Java's changes made since before the 1.0 release.
> Align JS SCM and textgraphicmanager with Java Suite's

- examples/js/hello-sdl/index.html
- examples/node/hello-sdl-tcp/index.js
- examples/node/hello-sdl/AppClient.js
- examples/webengine/hello-sdl/index.html
- lib/js/src/manager/SdlManager.js
- lib/js/src/manager/SystemCapabilityManager.js
- lib/js/src/manager/file/_FileManagerBase.js
- lib/js/src/manager/lifecycle/_LifecycleManager.js
- lib/js/src/manager/screen/_SoftButtonManagerBase.js
- lib/js/src/manager/screen/_TextAndGraphicManagerBase.js
- lib/js/src/manager/screen/_VoiceCommandManagerBase.js
- tests/managers/file/FileManagerTests.js
- tests/managers/lifecycle/LifecycleManagerTests.js
Fixes #276 
Fixes the example apps and SdlManager using the deprecated sendRpc method.
> Fix example apps to use sendRpcResolve

- lib/js/app.js
- package-lock.json
- package.json
This PR updates the version in the package.json to 1.1.0 and updates the build files.
> Feature/version update 1.1

- lib/js/src/manager/LifecycleConfig.js
Fixes the newly added setRpcNotificationListeners method to restrict listening RPCs to just notifications.
> setRpcNotificationListeners only accepts notification RPCs

- lib/js/src/rpc/messages/AddSubMenu.js
Fixes #265
Send an AddSubMenu RPC followed by another AddSubMenu RPC with the parentID set to the MenuID of the first SubMenu.
Adds the parentID parameter to the AddSubMenu RPC.
> Template Improvements: Additional SubMenus

- lib/js/src/manager/lifecycle/_LifecycleManager.js
- lib/js/src/rpc/enums/CharacterSet.js
- lib/js/src/rpc/structs/TextField.js
Fixes #267 
Run an example app, check the display capabilities in the SCM and verify that one of the new CharacterSets is present.
There are no updates to RPC messages.
Introduces the ability for apps to know what characters are supported by a head unit.
> [SDL 0202] Supported Character Sets

- lib/js/src/manager/SystemCapabilityManager.js
- lib/js/src/manager/lifecycle/_LifecycleManager.js
- lib/js/src/rpc/enums/SystemCapabilityType.js
- lib/js/src/rpc/structs/DriverDistractionCapability.js
- lib/js/src/rpc/structs/HMICapabilities.js
- lib/js/src/rpc/structs/SystemCapability.js
Fixes #266 
Enable driver distraction in the HMI and check the capability from the SystemCapabilityManager.
Run the RPC generator to add support for the DriverDistractionCapability and update the SystemCapabilityManager.
> [SDL 0152] Driver Distraction Improvements: Command List Limitations

- examples/js/hello-sdl/index.html
- examples/node/hello-sdl-tcp/index.js
- examples/node/hello-sdl/AppClient.js
- examples/webengine/hello-sdl/index.html
Previously the example apps would attempt to subscribe to non-RC buttons that would fail. This PR removes these buttons from the list of subscribed buttons.
> Example apps shouldn't subscribe to non-RC buttons

- generator/mapping.json
- generator/templates/scripts/TemplateConfiguration.js
Update the rpc_spec submodule to point to the branch located at https://github.com/smartdevicelink/rpc_spec/pull/288.
Run the RPC generator and check the TemplateConfiguration.js RPC struct file.
Adds deprecated get/set template methods to the TemplateConfiguration struct to ensure no breaking changes come from the added C++ keywords.
> update generator based on c++ keywords changes

- .github/PULL_REQUEST_TEMPLATE.md
> Update PR template to align with iOS / Java Suite

- lib/js/src/rpc/enums/SeekIndicatorType.js
- lib/js/src/rpc/messages/SetMediaClockTimer.js
- lib/js/src/rpc/structs/SeekStreamingIndicator.js
Fixes #346 
This PR is ready for review. The equivalent RPC spec PR should be approved before this PR should be merged: https://github.com/smartdevicelink/rpc_spec/pull/292
Updates SetMediaClockTimer to include backSeekIndicator and forwardSeekIndicator.
> Add new API to SetMediaClockTimer

- lib/js/src/manager/screen/utils/VoiceCommand.js
- lib/js/src/manager/screen/utils/_VoiceCommandUpdateOperation.js
- lib/js/src/protocol/_SdlPacket.js
- tests/managers/screen/VoiceCommandManagerTests.js
- tests/managers/screen/VoiceCommandUpdateOperationTests.js
Fixes #383 
N/A
Fixes reported linter issues in the various manager, protocol and test classes.
Run `npm run lint` to confirm the issues are resolved.
> Fix linter issues

- lib/js/src/rpc/enums/ImageFieldName.js
- lib/js/src/rpc/enums/TextFieldName.js
- lib/js/src/rpc/messages/AddCommand.js
- lib/js/src/rpc/messages/AddSubMenu.js
- lib/js/src/rpc/structs/MenuParams.js
Fixes #348 
Run the RPC generator for Main Menu UI updates.
> Main Menu UI Updates

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a lint validation requirement to the PR template.
> Include lint validation as a requirement in the PR template

- package-lock.json
- package.json
Resolves #410 
Updates the package version to 1.3.0, this version's upcoming release. The library will log the correct version when ran.
> Update package version to 1.3.0

- package-lock.json
- package.json
Fixes #459 
Updates the package.json and package-lock.json versions to 1.4.0 so the library will log 1.4.0 on startup.
> Update package version for 1.4

- lib/js/src/manager/screen/_ScreenManagerBase.js
Fixes #461 
This PR removes a reference to the SoftButtonManager's removed update method that would cause a crash in the library.
> Remove reference to SoftButtonManager's removed update method

- lib/js/src/manager/file/_DeleteFileOperation.js
- lib/js/src/manager/file/_FileManagerBase.js
- lib/js/src/manager/file/_UploadFileOperation.js
- lib/js/src/manager/file/filetypes/SdlArtwork.js
- lib/js/src/manager/file/filetypes/SdlFile.js
- tests/managers/file/FileManagerTests.js
- tests/managers/file/SdlFileTests.js
- tests/managers/file/UploadFileOperationTests.js
- tests/managers/index.js
Fixes #483 
This PR fixes the case where multiple upload/delete operations could be queued for the same file, resulting in the file being uploaded/deleted several times.
> Fix case where file can have multiple upload/delete tasks created for it

- examples/node/hello-sdl/AppClient.js
Remove the code that prints the App Auth Token.
Fixes #[No Issue Number]
This PR makes **[no]** API changes.
Remove the code that prints the App Auth Token.
- [X ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)
> Update AppClient.js - Remove the code that prints the App Auth Token.

- lib/js/src/manager/SystemCapabilityManager.js
Fixes #551 
Tests will be added in a separate PR, as there are missing SCM tests already.
Adds information about media clock formats and screen parameters in display capabilities, and window ID in the window capabilities.
> Add missing display capability info and window id

- lib/js/src/manager/SystemCapabilityManager.js
WindowTypeCapabilities object was created incorrectly.
Fixes #563
No Risk
- [ X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ X] I have verified that this PR passes lint validation
- [ X] I have run the unit tests with this PR
Ran with SCM Tests.
Modified the code to fix the issue with creating a WindowTypeCapabilities object.
Modified the code to fix the issue with creating a WindowTypeCapabilities object.
- [X ] SCM Tests
- [X ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)
> Create WindowTypeCapabilities object issue

- package-lock.json
- package.json
There are no code changes included in this PR.
Updates the version in the package.json and package-lock.json to 1.8.0.
> Package.json Version Update to 1.8.0

- examples/js/hello-sdl/package-lock.json
- examples/js/hello-sdl/package.json
- examples/webengine/hello-sdl/package-lock.json
- examples/webengine/hello-sdl/package.json
- package-lock.json
Resolves package vulnerabilities reported by npm by updating these packages to newer versions where the vulnerabilities are no longer present.
> Resolve package vulnerabilities
