generator/templates/RpcCreator_template.js, lib/js/src/rpc/RpcCreator.js
Fixes #132 
Adds a check for whether the jsonData has any content before being sent to the JSON marshaller.  The OnAudioPassThru notification has nothing in its json payload, which is what caused the JSON parse error. 
ex. send this rpc: 
```    
const rpc = new SDL.rpc.messages.PerformAudioPassThru()
.setSamplingRate(SDL.rpc.enums.SamplingRate.SamplingRate_44KHZ)
.setMaxDuration(1)
.setBitsPerSample(SDL.rpc.enums.BitsPerSample.BitsPerSample_16_BIT)
.setAudioType(SDL.rpc.enums.AudioType.PCM)
```
=> Check for jsonData content before sending to the json unmarshaller

lib/js/src/manager/screen/ScreenManagerBase.js, lib/js/src/manager/screen/SoftButtonManagerBase.js, lib/js/src/manager/screen/TextAndGraphicManagerBase.js
Fixes #153 
Has the screen manager return a boolean for commit success status. Also requires the update methods of the text and graphic manager and the soft button manager to have a boolean return. The clearing of the task queue has been removed for now, to avoid the case where a task called by a commit() is cleared, which may result in a forever-hanging promise.
=> Allow commit to return a boolean as to whether the update is successful

examples/node/hello-sdl/AppClient.js
Fixes #154 
Run the example app in /node/hello-sdl and observe that it does not count down until disconnects like the other example apps.
Example websocket no longer disposes of its server and does not send UnregisterAppInterface. There is also no countdown displayed as part of the app.
=> Example websocket app shouldn't dispose of the connection

lib/js/src/manager/lifecycle/LifecycleManager.js, lib/js/src/rpc/RpcRequest.js
_registerAppInterfaceResponse needs to be defined in the constructor of the LCM, and the _promise property of RpcRequest wasn't removed with the methods before
=> Remove unused private property and add a missing one in the constructor

lib/js/generate.js, lib/node/generate.js
Use the package.json to log the library version in the main builds
=> Log the library version using the package.json version property

lib/js/src/manager/SystemCapabilityManager.js
Fixes #165 
The bugfix makes it so that using the SCM to get app services returns an empty array when there are no app services available.
=> Define app service capability map immediately to avoid null issues

.eslintrc, package-lock.json, package.json
Fixes #170 
Install dev dependencies via npm, then run `npm run lint` to see the new jsDoc validation issues reported.
Adds jsDoc validation rules to the eslint configuration. Issues found via the validation will be resolve in a future PR.
=> jsDoc eslint validation

lib/js/app.js, lib/js/generate.js, lib/js/src/manager/SystemCapabilityManager.js
Fixes #172 
Nulls are checked for _createDisplayCapabilityList's extracted values to prevent a crash. Also, in queryCapability's sending a GetSystemCapability the `prototype` property is removed so that checking if `err` is an instance of `RpcResponse` works properly.
In addition, the es lint ignore rule has been added to the generate.js file so that the changes in app.js persist across builds
=> Protect against null values in SCM and have better error logging

generator/generator.py, generator/test/runner.py, generator/test/test_enums.py, generator/test/test_functions.py, generator/test/test_structs.py, generator/transformers/common_producer.py, generator/transformers/enums_producer.py, generator/transformers/functions_producer.py, generator/transformers/structs_producer.py
Fixes https://github.com/smartdevicelink/sdl_javascript_suite/issues/2
**Risk**
**Testing Plan**
Verify test app connectivity and that all unit tests pass.
**Summary**
avoid using keywords when generating RPC definitions.
**CLA**
=> apply reserved keywords mapping

GUIDELINES.md, generator/README.md, generator/templates/base_struct_function.js, generator/templates/scripts/RegisterAppInterfaceRequest.js, lib/js/src/rpc/RpcStruct.js
Makes RpcStruct's validateType a private method. Note that running the generator will change all the existing validateType usages to the correct method name
=> validateType is private

examples/js/hello-sdl/index.html, examples/node/hello-sdl-tcp/index.js, examples/node/hello-sdl/AppClient.js, examples/webengine/hello-sdl/index.html, lib/js/src/manager/AppConfig.js, lib/js/src/manager/lifecycle/_LifecycleManager.js
Removed the setIsMediaApp and isMediaApp methods from the AppConfig in favor of setting the _isMediaApp property based on the set AppHMITypes.
=> Remove setIsMediaApp and instead check hmitypes when setting

examples/node/hello-sdl-tcp/index.js, examples/node/hello-sdl/AppClient.js, examples/webengine/hello-sdl/index.html, lib/js/src/manager/AppConfig.js, lib/js/src/manager/SdlManager.js, lib/js/src/manager/lifecycle/_LifecycleManager.js
Removes HmiLanguageDesired property in favor of the already existing LanguageDesired property since having both is unnecessary.
=> Remove HmiLanguageDesired property and use the already existing LanguageDesired property

lib/js/app.js, lib/js/src/manager/SdlManager.js, lib/js/src/manager/SdlManagerListener.js, lib/js/src/manager/lifecycle/LifecycleConfigurationUpdate.js, lib/js/src/manager/lifecycle/_LifecycleManager.js
Fixes #221 
This PR is **[ready]** for review.
This PR makes **[no]** API changes.
Covered by existing unit tests
This PR fixes the managerShouldUpdateLifecycle behavior
* Added missing LifecycleConfigurationUpdate object
* Fixed uncaught (in promise) on the RegisterAppInterface request sending in _LifecycleManager
* Fixed wrong ChangeRegistration instantiation in SdlManager. _checkLifecycleConfiguration method
=> Bugfix managerShouldUpdateLifecycle

lib/js/src/manager/lifecycle/_LifecycleManager.js
Fixes #231 
Attaches a GenericResponse listener to every request sent through the SDL manager sendRpc method. This case is for older head units that respond with GenericResponse to a request that it does not recognize.
=> Fix hanging response if GenericResponse is returned

lib/js/src/manager/permission/_PermissionManagerBase.js
Fixes #228 
When a listener is attached for the permission manager, it will now immediately run logic to send an update to the listener, depending on the `PermissionGroupType` selected
=> Immediately invoke permission listener depending on conditions

lib/js/src/manager/SdlManager.js
Fixes #225 
Introduces a replacement method for `sendRpcs` that will return the array of responses even when some of them fail. Also adds an update handler callback that informs the user of completed RPCs and how many are remaining.
=> Add better sendRpcs method

lib/js/src/manager/LifecycleConfig.js, lib/js/src/manager/lifecycle/_LifecycleManager.js
Fixes #227 
Adds a getter and setter for resumption hash IDs to the lifecycle config. Listen for OnHashChange notifications to receive a hash ID, and then on a subsequent connection pass the string value to the lifecycle config in order to bring back some of the state of the previous connection, such as AddCommand menu items.
Add the build files when ready to review and merge in order to avoid merge conflicts.
=> Add resume hash to lifecycle config

lib/js/src/manager/SdlManager.js
Fixes #272 
Makes the `onUpdate` argument for the `sendRpcsResolve` and `sendSequentialRpcsResolve` methods optional.
=> Make second arg optional for sdl manager rpc methods

generator/templates/base_struct_function.js, generator/templates/enum_template.js, generator/transformers/common_producer.py, generator/transformers/enums_producer.py, generator/transformers/functions_producer.py
Fixes #296 
Run the `npm run build` command to run the generator and check a deprecated enum value.
Adds deprecated flags to the JS docs of deprecated enum values. This PR is dependent on the changes [here](https://github.com/smartdevicelink/sdl_javascript_suite/pull/295) and should be reviewed after those are approved.
=> Add deprecated flags to Enums when applicable

lib/js/src/rpc/RpcCreator.js, lib/js/src/rpc/enums/FunctionID.js, lib/js/src/rpc/enums/ImageFieldName.js, lib/js/src/rpc/messages/OnUpdateFile.js, lib/js/src/rpc/messages/OnUpdateSubMenu.js, lib/js/src/rpc/structs/DynamicUpdateCapabilities.js, lib/js/src/rpc/structs/WindowCapability.js
Fixes #268 
Use the example app and add listeners for the new `OnUpdateFile` and `OnUpdateSubMenu` notifications. Then send an `AddSubMenu` RPC with an icon that does not exist ('not_real.png'). When viewing the menu item, observe both new notifications as they come in. Additionally, check the new capability by checking a window capability in the SCM.
Adds the dynamicUpdateCapability to the WindowCapability and introduces the new OnUpdateFile and OnUpdateSubMenu notifications.
=> Update for Main Menu updating and Pagination

examples/js/hello-sdl/index.html, examples/node/hello-sdl-tcp/index.js, examples/node/hello-sdl/AppClient.js, examples/node/hello-sdl/index.js, examples/webengine/hello-sdl/index.html, lib/js/src/manager/screen/_ScreenManagerBase.js, lib/js/src/manager/screen/_SubscribeButtonManager.js, lib/js/src/manager/screen/_SubscribeButtonManagerBase.js
Fixes #118 
Run one of the example apps and press the AC button. The main text fields should portray a message saying the button was pressed.
Includes the new SubscribeButtonManager and Base classes. These managers can be used to easily subscribe to OnButtonPress and OnButtonEvent notifications for specific buttons. This PR also updates the example apps to support the functionality of the new managers.
=> [SDL 0279] Screen Manager Subscribe Buttons

lib/js/src/protocol/_SdlProtocolBase.js, lib/js/src/protocol/enums/_ControlFrameTags.js
Fixes #243 
Use the following code snippet to start services that will be used to trigger a NAK. This can be done from any of the example apps.
```
const session = this._sdlManager._lifecycleManager._sdlSession;
// serviceType is one of [Audio, Video, RPC]
// isProtected is whether the service should be protected
session.startService(SDL.protocol.enums._ServiceType[serviceType], session.getSessionId(), isProtected);
```
The previous snippet can be used to trigger a StartServiceNAK. To observe the new reason param in the NAK, modify the _SdlProtocolBase's _handleStartServiceNAK method to match the following code snippet.
```
const serviceType = sdlPacket.getServiceType();
const protocolVersion = sdlPacket.getVersion();
if …
```
=> Add reason param to NAKBase and update protocol to v5.3.0

generator/templates/enum_template.js, lib/js/src/manager/file/enums/StaticIconName.js, lib/js/src/manager/permission/enums/PermissionGroupStatus.js, lib/js/src/manager/permission/enums/PermissionGroupType.js, lib/js/src/protocol/enums/_FrameType.js, lib/js/src/protocol/enums/_ServiceType.js, lib/js/src/transport/enums/TransportType.js, lib/js/src/util/Enum.js
Fixes #312 
Adds a new method for all enums `.values()` to return a list of all values available for the enum
=> Add .values method for all enums

lib/js/src/manager/SystemCapabilityManager.js, lib/js/src/manager/_SubManagerBase.js, lib/js/src/manager/screen/_ScreenManagerBase.js, lib/js/src/manager/screen/_TextAndGraphicManagerBase.js, lib/js/src/manager/screen/_TextAndGraphicState.js, lib/js/src/manager/screen/_TextAndGraphicUpdateOperation.js, lib/js/src/rpc/enums/FunctionID.js, lib/js/src/rpc/enums/ImageFieldName.js
Fixes #175 
Example code snippet for updating the screen layout from the example apps:
```
await screenManager.changeLayout(
new SDL.rpc.structs.TemplateConfiguration()
.setTemplate(SDL.rpc.enums.PredefinedLayout.TEXTBUTTONS_WITH_GRAPHIC)
);
```
Adds a new operation to the ScreenManager for changing the HMI TemplateConfiguration.
Also updates the setters in the TextAndGraphicManagerBase to call sdlUpdate instead of update to avoid cases where a task would be added which could not be run because isDirty was never set.
=> Screen Manager Template Management

.eslintrc, package-lock.json, package.json, rollup.config.js
Switches out vulnerable packages.
Replaces rollup-plugin-uglify with rollup-plugin-terser
Updates rollup-plugin-node-builtins and rollup-plugin-node-globals with vulnerability fixes. Due to lack of updates in those packages, forks of them will be used instead.
=> Bugfix/vulnerabilities 1.1

generator/transformers/common_producer.py
Fixes #324 
This PR fixes an issue in the RPC Generator where it cuts off the JSdoc comments after TODO
=> Update generator to not strip todos

examples/js/hello-sdl/index.html, examples/node/hello-sdl-tcp/index.js, examples/node/hello-sdl/AppClient.js, examples/webengine/hello-sdl/index.html
Fixes #321 and #320 and #323 
This PR **ready** for review.
Will be tested manually
Logic of sending AddCommand and SubscribeButton for sample WEB_VIEW application were moved from OnHmiStatus callback to permissions change callback. This is more reliable way to trigger sending of initial RPCs as changing of HMI level is not always guarantees that RPC is allowed. Also, this is a more simple way to execute some blocks of code just once.
=> Fix request sending on permissions change

lib/js/src/manager/screen/_TextAndGraphicUpdateOperation.js
Fixes #326 
Start a TextAndGraphicUpdateOperation without updating the text alignment. Previously it would error, but now it should succeed in the update.
Adds a check for the text alignment field in the TextAndGraphicUpdateOperation class
=> Add null/undefined check for text alignment

generator/templates/base_struct_function.js, generator/test/runner.py, generator/test/test_enums.py, generator/test/test_functions.py, generator/test/test_structs.py, generator/transformers/common_producer.py
From the generator directory, run `python3 test/runner.py`. There should be no failing tests.
Some of the unit tests for the RPC generator were failing. This PR fixes the failing tests, without changing the generator itself or any of the generated files.
=> Fix failing RPC generator unit tests

lib/js/src/manager/screen/_VoiceCommandManagerBase.js, lib/js/src/manager/screen/utils/VoiceCommand.js, lib/js/src/manager/screen/utils/_VoiceCommandUpdateOperation.js, tests/managers/index.js, tests/managers/screen/VoiceCommandManagerTests.js, tests/managers/screen/VoiceCommandUpdateOperationTests.js
Fixes #344 
Run the manager tests
Uses the queuing system to manage the addition and removal of voice commands. Unit tests are created to reflect the new behavior.
=> Refactor to use queues and create unit tests

lib/js/src/manager/file/_FileManagerBase.js, lib/js/src/manager/file/filetypes/SdlFile.js, lib/js/src/manager/screen/_SoftButtonManagerBase.js, lib/js/src/manager/screen/_TextAndGraphicUpdateOperation.js
Fixes #365 
Updates the SdlFile class to include the overwrite property, and updates the SoftButtonManager and the TextAndGraphicManager to recognize the use of the overwrite value.
=> Make managers aware of artwork overwrite property

lib/js/src/rpc/enums/VehicleDataType.js, lib/js/src/rpc/messages/GetVehicleData.js, lib/js/src/rpc/messages/GetVehicleDataResponse.js, lib/js/src/rpc/messages/OnVehicleData.js, lib/js/src/rpc/messages/SubscribeVehicleData.js, lib/js/src/rpc/messages/SubscribeVehicleDataResponse.js, lib/js/src/rpc/messages/UnsubscribeVehicleData.js, lib/js/src/rpc/messages/UnsubscribeVehicleDataResponse.js, lib/js/src/rpc/structs/SeatOccupancy.js, lib/js/src/rpc/structs/SeatStatus.js, tests/Test.js, tests/node/rpc/enums/VehicleDataTypeTests.js, tests/node/rpc/messages/GetVehicleDataResponseTests.js, tests/node/rpc/messages/GetVehicleDataTests.js, tests/node/rpc/messages/OnVehicleDataTests.js, tests/node/rpc/messages/SubscribeVehicleDataResponseTests.js, tests/node/rpc/messages/SubscribeVehicleDataTests.js, tests/node/rpc/messages/UnsubscribeVehicleDataResponseTests.js, tests/node/rpc/messages/UnsubscribeVehicleDataTests.js, tests/node/rpc/structs/SeatOccupancyTests.js, tests/node/rpc/structs/SeatStatusTests.js
Fixes #336
Added unit tests cover [[SDL 0262] New vehicle data SeatOccupancy](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0262-New-vehicle-data-SeatOccupancy.md) changes
* `VehicleDataType` enum contains additional value `"VEHICLEDATA_SEATOCCUPANCY"`
* each of the properties in the struct `SeatStatus` can be received from HMI
* each of the properties in the struct `SeatOccupancy` can be received from HMI
* `SubscribeVehicleData`, `UnsubscribeVehicleData`, `GetVehicleData` request messages can be sent with `seatOccupancy` parameter defined as boolean value
* `SubscribeVehicleData`, `UnsubscribeVehicleData` response messages contain `seatOccupancy` parameter defined as `VehicleDataResult` struct
* `GetVehicleData `, …
=> [SDL-0262] New vehicle data SeatOccupancy

generator/templates/base_template.js
Fixes #372 
N/A
N/A
Adds a check to the generator to make sure not to import a file into the same file for the RPC classes.
=> Do not import a file that leads to the same file

lib/js/src/manager/lifecycle/_LifecycleManager.js
Fixes #375 
_LifecycleManager.MAX_RPC_VERSION is updated to 7.1.0. No additional tests or changes needed.
=> Update RPC version to 7.1.0

lib/js/src/rpc/enums/TextFieldName.js, lib/js/src/rpc/messages/Show.js
Fixes the rpc_spec issue brought up in https://github.com/smartdevicelink/rpc_spec/issues/276
Runs the generated fix made by this rpc_spec PR: https://github.com/smartdevicelink/rpc_spec/issues/276
Show.setMediaClock is now deprecated
TextFieldName.mediaClock is now deprecated
=> Include missing deprecation tags

lib/js/src/rpc/messages/RegisterAppInterface.js
Fixes the rpc_spec issue brought up in https://github.com/smartdevicelink/rpc_spec/issues/206
Runs the generated fix made by this rpc_spec PR: https://github.com/smartdevicelink/rpc_spec/pull/311
RegisterAppInterface.AppInfo now shows 4.2.0 as the correct version it was introduced.
=> Fix RAI appInfo since attribute

lib/js/src/rpc/messages/EncodedSyncPData.js, lib/js/src/rpc/messages/EncodedSyncPDataResponse.js, lib/js/src/rpc/messages/OnEncodedSyncPData.js
Fixes the rpc_spec issue brought up in https://github.com/smartdevicelink/rpc_spec/issues/237
Runs the generated fix made by this rpc_spec PR: https://github.com/smartdevicelink/rpc_spec/pull/310
EncodedSyncPData, EncodedSyncPDataResponse, and OnEncodedSyncPData are now deprecated.
=> Deprecate SyncPData functions

generator/templates/base_struct_function.js
Fixes #380 
Adds since and additional deprecation information to the getter methods. Also corrects an issue where getter methods were tagged as deprecated because of the class being deprecated, and not because the method itself was deprecated.
=> Align getter and setter rules in generator

lib/js/src/rpc/messages/SetMediaClockTimer.js
Fixes #347 
This PR is ready for review. The equivalent RPC spec PR should be approved before this PR should be merged: https://github.com/smartdevicelink/rpc_spec/pull/294
Updates SetMediaClockTimer to include the count rate.
=> Add countRate to SetMediaClockTimer

lib/js/src/rpc/enums/DoorStatusType.js, lib/js/src/rpc/structs/BodyInformation.js, lib/js/src/rpc/structs/DoorStatus.js, lib/js/src/rpc/structs/GateStatus.js, lib/js/src/rpc/structs/RoofStatus.js, tests/Test.js, tests/node/rpc/enums/DoorStatusTypeTests.js, tests/node/rpc/structs/BodyInformationTests.js, tests/node/rpc/structs/DoorStatusTests.js, tests/node/rpc/structs/GateStatusTests.js, tests/node/rpc/structs/RoofStatusTests.js
Fixes #338
Added unit tests cover [[SDL-0255] Enhance BodyInformation vehicle data](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0255-Enhance-BodyInformation-vehicle-data.md) changes
* each of the properties in the struct `DoorStatus` can be received from HMI
* each of the values in the enum `DoorStatusType ` can be received from HMI
* each of the properties in the struct `GateStatus` can be received from HMI
* each of the properties in the struct `RoofStatus` can be received from HMI
* `doorStatuses`, `gateStatuses`, `roofStatuses` properties are present in `BodyInformation` struct
* `GetVehicleData` response message contains `bodyInformation` parameter with `doorStatuses`, `gateStatuses`, `roofStatuses` properties
Core …
=> [SDL-0255] Enhance BodyInformation vehicle data

.gitmodules, lib/js/src/rpc/structs/VideoStreamingCapability.js, lib/js/src/streaming/video/_VideoStreamingParameters.js, tests/node/streaming/video/VideoStreamingParametersTest.js
Fixes #115
VideoStreamingParametersTest will partially cover this change.
Implementing SDL 0274: Add preferred FPS to VideoStreamingCapability.
* N/A
* Adding preferredFPS into VideoStreamingCapability.
* N/A
- N/A
=> SDL 0274: Add preferred FPS to VideoStreamingCapability

lib/js/src/rpc/enums/TextFieldName.js
Fixes #349 
This PR is ready for review. The equivalent RPC spec PR and Core PR should be approved before this PR is reviewed and merged: https://github.com/smartdevicelink/rpc_spec/pull/303, and https://github.com/smartdevicelink/sdl_core/pull/3595
Adds enums to the TextFieldName class
=> [SDL 0305] Homogenize TextFieldName

lib/js/src/protocol/_SdlProtocolBase.js
Fixes #387 
* The SdlProtocolBase will no longer attempt to incorrectly set the protocol version to v5.1 when the major version of the first packet header is `> 5`.
=> Fix SdlProtocolBase setting wrong protocol version

lib/js/src/manager/SystemCapabilityManager.js
Fixes #389 
Adds null checks before attempt to set arrays for the DisplayCapability in the SCM.
=> Perform null checks for setting image and text fields

lib/js/src/rpc/RpcStruct.js
Fixes #385 
Fixes the case where setting a Struct, Enum, or Array property of an RPC to null would throw an error. These properties can now be set to null, since the marshaller already ignores null/undefined properties.
=> Update RpcStruct._validateType to not throw error for a null value

generator/templates/base_struct_function.js, lib/js/src/manager/permission/enums/PermissionGroupStatus.js, lib/js/src/manager/screen/_ScreenManagerBase.js, lib/js/src/protocol/_MessageFrameDisassembler.js
Fixes #391 
* Fixes `Initalizes` typos to correctly say `Initializes`.
=> Fix initalize typos

lib/js/src/manager/file/enums/StaticIconName.js
Fixes #398 
Fixes the spelling of `AUXILLARY_AUDIO` in the StaticIconName enum.
=> Fix auxillary typo in StaticIconName

lib/js/src/manager/screen/choiceset/ChoiceSet.js, lib/js/src/manager/screen/utils/AlertView.js, tests/managers/screen/AlertViewTests.js, tests/managers/screen/choiceset/ChoiceSetTests.js
Fixes #396 
This PR makes no API changes. (Choice Set is not part of an official release yet)
Includes tests to check sanitization of timeout values
Adds better checks to setting and getting the choice set timeouts. Also includes a missing default timeout parameter in the choice set class and adds tests for those. Timeout values will now behave well when attempting to get their values.
=> Fix setting choice set timeouts

examples/js/hello-sdl/index.html, examples/node/hello-sdl-tcp/index.js, examples/node/hello-sdl/AppClient.js, examples/webengine/hello-sdl/index.html, lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js
Includes updates to each of the example apps to support the AlertManager and ChoiceSetManager.
* Includes a bug fix for the Vanilla JS build being unable to properly preload ChoiceCells.
=> Update Example apps for 1.3

lib/js/src/manager/permission/_PermissionManagerBase.js
Fixes #403 
Tested with 7.1.0 RC
Fixes when the permission manager's _notifyListeners method returns so that all filters are checked.
=> Fix positioning of return statement in PermissionManager

lib/js/src/manager/screen/utils/_PresentAlertOperation.js
Fixes #406 
Testing against 7.1.0 RC
Removes an outer if statement in the PresentAlertOperation that only allows the inner code to run if alert audio files are not supported.
=> Fix check for supported audio files in AlertManager

lib/js/src/manager/screen/_ScreenManagerBase.js, tests/managers/screen/ScreenManagerTests.js
Fixes #405 
This PR fixes the issue that would cause the ScreenManager's sub-managers to generate overlapping button IDs that trigger the same button listeners. The AlertManager will now consider the SoftButtonManager's button IDs and vice versa.
=> ScreenManager Overlapping Button IDs

lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js
Fixes #411 
Tested with RC 7.1.0
Adds a null check to the choicesetmanager's _pendingPresentationSet getChoiceSetSelectionListener method before invoking it.
=> Perform null checks for choice set selection listener in manager

lib/js/src/manager/screen/_TextAndGraphicManager.js
Fixes #417 
The blank artwork used by the TextAndGraphicManager will now be uploaded as a persistent file to avoid re-uploading.
=> Blank artwork should be persistent

lib/js/src/manager/screen/choiceset/KeyboardListener.js, lib/js/src/manager/screen/choiceset/_PresentChoiceSetOperation.js, lib/js/src/manager/screen/choiceset/_PresentKeyboardOperation.js
Fixes #419 
Tested against the latest sdl_core build from the develop branch. Need to give Keyboard permissions in the policy table.
Fixes an alignment issue with the KeyboardListener. `onKeyboardInputMaskHasChanged` is now `OnKeyboardDidUpdateInputMask`.
=> Align Keyboard Listener

lib/js/src/manager/permission/_PermissionManagerBase.js
Fixes #422 
This PR fixes the case where an app would receive an OnPermissionsChange notification from core and clone its old PermissionItems but not convert them to PermissionItems.
=> PermissionManager should convert old permissions to RPCStructs after cloning them

lib/js/src/manager/screen/utils/VoiceCommand.js, lib/js/src/manager/screen/utils/_VoiceCommandUpdateOperation.js, tests/managers/screen/VoiceCommandManagerTests.js
Fixes #430 
Adds a unit test to ensure that the VoiceCommand class removes all duplicates.
The VoiceCommand class will now convert the provided string array into a Set to ensure uniqueness among the strings, then convert back to an array.
Fixes the case where VoiceCommands could be sent with duplicates of the same string.
=> Voice command should not contain duplicate strings

lib/js/src/manager/screen/_VoiceCommandManagerBase.js, tests/managers/screen/VoiceCommandManagerTests.js
Fixes #432 
* Setting multiple voice commands with the VoiceCommandManager will check that each voice command contains unique strings from the other voice commands.
=> check whether separate voice commands contain the same string

lib/js/src/manager/screen/_VoiceCommandManagerBase.js, tests/managers/screen/VoiceCommandManagerTests.js
Fixes #431 
* Removes empty voice commands from the list of voice commands to be set by the operation and does not perform an operation if there are no voice commands left.
=> Fix for voice command that contains no string should be removed

lib/js/src/manager/screen/_VoiceCommandManagerBase.js, tests/managers/screen/VoiceCommandManagerTests.js
Fixes #440 
* Setting an empty voice command array through the screen manager no longer fails and will delete all current voice commands. There are also new unit tests added to confirm the new functionality behaves as expected.
=> Sending an empty voice command array should delete all current voice commands

lib/js/src/manager/lifecycle/_LifecycleManager.js, tests/managers/lifecycle/LifecycleManagerTests.js
Fixes #446 
[Describe the unit tests and behaviors added in this PR]
* Updates the lifecycle manager to save the initial display capabilities for type MEDIA for future use as a workaround for a Sync 3 media capabilities bug.
=> Update lifecycle manager to work around Sync 3 media capabilities bug

lib/js/src/manager/screen/_VoiceCommandManagerBase.js
Fixes #448 
* This PR fixes the JS Docs for VoiceCommandManager setVoiceCommand to correctly state that the Promise returned resolves after the task to update the commands has been added to the task queue.
=> Fix JS Docs for setVoiceCommand

lib/js/src/manager/screen/_ScreenManagerBase.js, lib/js/src/manager/screen/_VoiceCommandManagerBase.js, lib/js/src/manager/screen/utils/VoiceCommand.js, lib/js/src/manager/screen/utils/_VoiceCommandUpdateOperation.js, tests/managers/screen/VoiceCommandManagerTests.js, tests/managers/screen/VoiceCommandUpdateOperationTests.js
Fixes #433 
Added unit tests to verify that VoiceCommands are added/deleted correctly.
* The VoiceCommandManager will no longer delete a VoiceCommand if the VoiceCommand is going to be immediately added again as part of the same update operation. Below is sample code that can be used to test the functionality. Option 1-3 will be added as part of the first operation. The second operation will delete Option 3 and add Option 4 while leaving Option 1/2 untouched.
```
const voiceCommands = [
new SDL.manager.screen.utils.VoiceCommand(['Option 1'], () => {}),
new SDL.manager.screen.utils.VoiceCommand(['Option 2'], () => {}),
new SDL.manager.screen.utils.VoiceCommand(['Option 3'], () => {}),
];
await screenManager.setVoiceCommands(voiceCommands);
const …
```
=> Fix manager to not delete and set identical voice commands

lib/js/src/manager/SystemCapabilityManager.js
Fixes #450 
If display capabilities uses the incorrect string 'NON_MEDIA' in templatesAvailable, it will be fixed to the correct string 'NON-MEDIA'.
=> Fix case where head unit uses incorrect name for PredefinedLayout NON-MEDIA

lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js, tests/managers/screen/choiceset/ChoiceSetManagerTests.js
Fixes #445 
This PR updates the screen manager (menu manager and choice manager) to check the uniqueness of cells based on available screen properties on RPC v7.1+
=> Choice Cells and Menu Cells do not take which properties are available into account for uniqueness

lib/js/src/manager/SystemCapabilityManager.js
Fixes #465 
Adds a null check to getting available templates in one of the SCM's methods to prevent a reference error.
=> Do a null check for the templates available in the window capability

lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js, lib/js/src/manager/screen/choiceset/_PreloadChoicesOperation.js, tests/managers/screen/choiceset/PreloadChoicesOperationTests.js
Fixes #470 
This PR updates the ChoiceSet Manager to handle failures individually when preloading ChoiceCells. Successful choices will be added to the list of preloaded cells but failed cells will not be added.
=> Don't add choice cells to list of preloaded cells if they failed to preload

lib/js/src/manager/_SubManagerBase.js
Fixes #472 
Fixes the case where on an OnHmiStatus SystemContext change, the SubManagerBase is able to run tasks again but does not immediately restart the task queue. This would leave some tasks idle in the queue until another task was added.
=> Fix submanager to invoke the task queue when changing the system context

lib/js/src/manager/screen/_SoftButtonManagerBase.js
Fixes #485 
Adds an invocation to the task queue after tasks are able to run again in the SoftButtonManager. See MenuManager's same named method for comparison.
=> Add invokeTaskQueue to SoftButtonManager

lib/js/src/manager/screen/choiceset/_PreloadPresentChoicesOperation.js
Fixes #495 
Change the return value of _preloadCellArtworks to be correct
=> Fix boolean return in _preloadCellArtworks

lib/js/src/manager/screen/choiceset/_PreloadPresentChoicesOperation.js
Fixes #497 
Moves the teardown of the keyboard listener to the beginning of the finishOperation to prevent hanging listeners from continuing to function after the operation ends.
=> Make detaching listener happen all the time in finishOperation

lib/js/src/manager/screen/_SoftButtonReplaceOperation.js
Fixes #515 
Checks if soft button capabilities in the softbuttonreplaceoperation class is null first before calling its method.
=> Check for null before attempting to call _supportsSoftButtonImages

lib/js/src/manager/screen/_VoiceCommandManagerBase.js
Fixes #529 
Core version / branch / commit hash / module tested against: 8.0.0
HMI name / version / branch / commit hash / module tested against: 0.11.0
Adds warning logs for when a submitted voice string is empty or is blank, and when no valid strings exist for a voice command.
=> Add warnings for invalid voice command strings

lib/js/src/manager/screen/utils/_PresentAlertOperation.js
Fixes #526 
Core version / branch / commit hash / module tested against: 8.0.0
HMI name / version / branch / commit hash / module tested against: 0.11.0
Adds checks to the `supportsSoftButtonImages` method in `_PresentAlertOperation`  to avoid accessing properties in potentially null values.
=> Fix null access error in _PresentAlertOperation

examples/js/hello-sdl/readme.md
Fixes #537 
The old instructions in the vanilla JS example app readme involved having 2 terminal windows open where one of them was running the proxy.jar file. The proxy.jar file is no longer required to run the example app, so it was removed from the instructions, but the readme still mentions having 2 terminal windows open which is confusing.
=> Vanilla JS readme typo still mentions needing two terminal windows

lib/js/src/manager/file/filetypes/SdlArtwork.js
Fixes #546 
Tested on Manticore for SDL Core v8.1.0
When cloning an SdlArtwork instance, do not clone the cached _imageRPC object with it. This prevents a case where the user changes the file name but the cached object does not update and the T&G manager uses that outdated information.
=> Do not clone _imageRPC with SdlArtwork

lib/js/src/manager/screen/_TextAndGraphicUpdateOperation.js, tests/managers/screen/TextAndGraphicUpdateOperationTests.js
Fixes #559 
When sending a show and updating the internal state of the text and graphic manager, remember the template configuration that was set.
=> Update T&G current screen data with template config

lib/js/src/manager/screen/_TextAndGraphicManagerBase.js, lib/js/src/manager/screen/_TextAndGraphicUpdateOperation.js, tests/managers/screen/TextAndGraphicUpdateOperationTests.js
Fixes #554 
Add tests for the new _updateTargetStateWithErrorState method
When sending updates of invalid data followed by valid data to the T&G manager, the valid data will not be thrown out with the invalid data.
Resolved an issue with _updatePendingOperationsWithNewScreenData where the wrong identifier was used in the for loop for looping over tasks.
Also fixed _TextAndGraphicUpdateOperation to properly await on sending shows so that the task does not immediately complete.
Fixed variables in test returning undefined due to non-existent SDL.rpc.enums.MetadataType.MEDIA_TITLE value.
=> Fix T&G issues with updating state rapidly

lib/js/src/manager/screen/utils/_PresentAlertOperation.js, tests/managers/screen/PresentAlertOperationTests.js
Fixes #558 
Tests the Alert RPC generation when an AlertView has an icon
_PresentAlertOperation now keeps track of uploaded artwork names and uses it to check whether to attach the AlertView icon to the Alert RPC.
=> Apply fix to alert icon not uploading
